# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: products.list.title

# Model Form Field configuration
form: $/crydesign/mallcraft/models/product/fields.yaml

# Model Class name
modelClass: Crydesign\Mallcraft\Models\Product

# Default redirect location
defaultRedirect: crydesign/mallcraft/products

# Create page
create:
    title: products.form.create_title
    redirect: crydesign/mallcraft/products/update/:id
    redirectClose: crydesign/mallcraft/products

# Update page
update:
    title: products.form.update_title
    redirect: crydesign/mallcraft/products
    redirectClose: crydesign/mallcraft/products

# Preview page
preview:
    title: backend::lang.form.preview_title
